//
// Project: AudioManager
// Author: Mark Battistella
// Website: https://markbattistella.com
//

import Foundation

/// Represents a system sound with predefined raw values for playback.
public enum SystemSound: String {
    
    // Modern sounds
    case airdropInvite = "Modern/airdrop_invite.caf"
    case calendarAlertChord = "Modern/calendar_alert_chord.caf"
    case cameraShutterBurst = "Modern/camera_shutter_burst.caf"
    case cameraShutterBurstBegin = "Modern/camera_shutter_burst_begin.caf"
    case cameraShutterBurstEnd = "Modern/camera_shutter_burst_end.caf"
    case smsAlertAurora = "Modern/sms_alert_aurora.caf"
    case smsAlertBamboo = "Modern/sms_alert_bamboo.caf"
    case smsAlertCircles = "Modern/sms_alert_circles.caf"
    case smsAlertComplete = "Modern/sms_alert_complete.caf"
    case smsAlertHello = "Modern/sms_alert_hello.caf"
    case smsAlertInput = "Modern/sms_alert_input.caf"
    case smsAlertKeys = "Modern/sms_alert_keys.caf"
    case smsAlertNote = "Modern/sms_alert_note.caf"
    case smsAlertPopcorn = "Modern/sms_alert_popcorn.caf"
    case smsAlertSynth = "Modern/sms_alert_synth.caf"
    
    // New sounds
    case anticipate = "New/Anticipate.caf"
    case bloom = "New/Bloom.caf"
    case calypso = "New/Calypso.caf"
    case chooChoo = "New/Choo_Choo.caf"
    case descent = "New/Descent.caf"
    case fanfare = "New/Fanfare.caf"
    case ladder = "New/Ladder.caf"
    case minuet = "New/Minuet.caf"
    case newsFlash = "New/News_Flash.caf"
    case noir = "New/Noir.caf"
    case sherwoodForest = "New/Sherwood_Forest.caf"
    case spell = "New/Spell.caf"
    case suspense = "New/Suspense.caf"
    case telegraph = "New/Telegraph.caf"
    case tiptoes = "New/Tiptoes.caf"
    case typewriters = "New/Typewriters.caf"
    case update = "New/Update.caf"
    
    // Base sounds
    case receivedMessage = "ReceivedMessage.caf"
    case ringerChanged = "RingerChanged.caf"
    case simToolkitCallDropped = "SIMToolkitCallDropped.caf"
    case simToolkitGeneralBeep = "SIMToolkitGeneralBeep.caf"
    case simToolkitNegativeACK = "SIMToolkitNegativeACK.caf"
    case simToolkitPositiveACK = "SIMToolkitPositiveACK.caf"
    case simToolkitSMS = "SIMToolkitSMS.caf"
    case sentMessage = "SentMessage.caf"
    case swish = "Swish.caf"
    case tink = "Tink.caf"
    case tock = "Tock.caf"
    case voicemail = "Voicemail.caf"
    case alarm = "alarm.caf"
    case beepBeep = "beep-beep.caf"
    case beginRecord = "begin_record.caf"
    case beginVideoRecord = "begin_video_record.caf"
    case ctBusy = "ct-busy.caf"
    case ctCallWaiting = "ct-call-waiting.caf"
    case ctCongestion = "ct-congestion.caf"
    case ctError = "ct-error.caf"
    case ctKeytone2 = "ct-keytone2.caf"
    case ctPathAck = "ct-path-ack.caf"
    case dtmf0 = "dtmf-0.caf"
    case dtmf1 = "dtmf-1.caf"
    case dtmf2 = "dtmf-2.caf"
    case dtmf3 = "dtmf-3.caf"
    case dtmf4 = "dtmf-4.caf"
    case dtmf5 = "dtmf-5.caf"
    case dtmf6 = "dtmf-6.caf"
    case dtmf7 = "dtmf-7.caf"
    case dtmf8 = "dtmf-8.caf"
    case dtmf9 = "dtmf-9.caf"
    case dtmfPound = "dtmf-pound.caf"
    case dtmfStar = "dtmf-star.caf"
    case endRecord = "end_record.caf"
    case endVideoRecord = "end_video_record.caf"
    case jblAmbiguous = "jbl_ambiguous.caf"
    case jblBegin = "jbl_begin.caf"
    case jblCancel = "jbl_cancel.caf"
    case jblConfirm = "jbl_confirm.caf"
    case jblNoMatch = "jbl_no_match.caf"
    case lock = "lock.caf"
    case longLowShortHigh = "long_low_short_high.caf"
    case lowPower = "low_power.caf"
    case mailSent = "mail-sent.caf"
    case middle9ShortDoubleLow = "middle_9_short_double_low.caf"
    case newMail = "new-mail.caf"
    case photoShutter = "photoShutter.caf"
    case shake = "shake.caf"
    case shortDoubleHigh = "short_double_high.caf"
    case shortDoubleLow = "short_double_low.caf"
    case shortLowHigh = "short_low_high.caf"
    case smsReceived1 = "sms-received1.caf"
    case smsReceived2 = "sms-received2.caf"
    case smsReceived3 = "sms-received3.caf"
    case smsReceived4 = "sms-received4.caf"
    case smsReceived5 = "sms-received5.caf"
    case smsReceived6 = "sms-received6.caf"
    case sqAlarm = "sq_alarm.caf"
    case sqBeepBeep = "sq_beep-beep.caf"
    case sqLock = "sq_lock.caf"
    case sqTock = "sq_tock.caf"
    case tweetSent = "tweet_sent.caf"
    case unlock = "unlock.caf"
    case ussd = "ussd.caf"
    case vcEnded = "vc~ended.caf"
}
