//
// Project: AudioManager
// Author: Mark Battistella
// Website: https://markbattistella.com
//

import Foundation

/// A protocol that represents a system sound, with the ability to convert to a raw string value.
/// Types conforming to `SystemSoundRepresentable` must have a `RawValue` of type `String` and
/// provide a folder name where the sound file is located.
internal protocol SystemSoundRepresentable: RawRepresentable where RawValue == String {

    /// The name of the folder where the sound files are stored.
    /// - Important: This folder name should correctly correspond to a subdirectory in the
    /// project's file structure to ensure sound file accessibility.
    var folderName: String { get }
}

/// Default implementation for `SystemSoundRepresentable` to create a file path for a system sound.
/// Provides a calculated `path` property that constructs the full path of the sound file.
extension SystemSoundRepresentable {

    /// The full path for the sound file, generated by concatenating the base path, folder name,
    /// and the raw value.
    ///
    /// - Note: `SystemSound.basePath` should be defined to provide the root directory for all
    /// system sounds.
    internal var path: String {
        SystemSound.basePath + folderName + rawValue
    }
}
